version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/wvi
    ports:
      - 8100:8000
    image: app:wvi
    container_name: wvi_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    ports:
      - '3306:3306'
    image: mysql
    environment:
      MYSQL_DATABASE: 'wvi-app-db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    command: --default-authentication-plugin=mysql_native_password
    restart: always