# Generated by Django 4.1.7 on 2023-04-27 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wvi', '0002_child_gender_alter_child_age_alter_child_community_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_participation', models.IntegerField(null=True)),
                ('family_participation', models.IntegerField(null=True)),
                ('child_support', models.IntegerField(null=True)),
                ('family_support', models.IntegerField(null=True)),
                ('benefit_support', models.IntegerField(null=True)),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wvi.child')),
            ],
        ),
        migrations.CreateModel(
            name='ChildRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.TextField(null=True)),
                ('status', models.TextField(null=True)),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wvi.child')),
                ('kader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wvi.kader')),
            ],
        ),
    ]
