# Generated by Django 4.1.7 on 2023-04-28 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wvi', '0003_kader_participation_childrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childrecord',
            name='kader_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wvi.kader'),
        ),
    ]
