# Generated by Django 4.1.7 on 2023-05-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wvi', '0004_alter_childrecord_kader_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='rt',
            field=models.TextField(null=True),
        ),
    ]
