# Generated by Django 4.1.7 on 2023-05-05 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wvi', '0005_child_rt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(null=True)),
                ('creation_date', models.DateField(null=True)),
                ('mail_action', models.TextField(null=True)),
                ('due_date_field', models.DateField(null=True)),
                ('due_date_system', models.DateField(null=True)),
                ('days_before_due_date_field', models.DateField(null=True)),
                ('days_before_due_date_system', models.DateField(null=True)),
                ('status', models.TextField(null=True)),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wvi.child')),
                ('kader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wvi.kader')),
            ],
        ),
    ]
