# Generated by Django 4.1.7 on 2023-05-12 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wvi', '0006_correspondence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_due_date_field', models.IntegerField(null=True)),
                ('target_child', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='kader_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wvi.kader'),
        ),
    ]
