# Generated by Django 4.1.7 on 2023-05-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wvi', '0007_parameters_alter_correspondence_kader_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondence',
            name='days_before_due_date_field',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='days_before_due_date_system',
            field=models.IntegerField(null=True),
        ),
    ]
