# Generated by Django 4.1.7 on 2023-05-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wvi', '0008_alter_correspondence_days_before_due_date_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
